"""`Inmueble` aggregate root and its lifecycle state machine.

Business rules and states come from
`openspec/changes/hu-001/specs/inmuebles/spec.md` (Requirements: "Creación de
publicación de inmueble", "Carga de fotos en la publicación", "Estado inicial
de la publicación", "Despublicación temporal del inmueble" and "Transición
automática a no disponible") and from `design.md` decisión 2
(`MAX_FOTOS_INMUEBLE` as a named constant) and decisión 4 (`no_disponible` is
reached via a direct method call from a future use case, not via events).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum

from inmuebles.domain.foto import FotoInmueble
from shared.domain.exceptions import DomainValidationError

MIN_FOTOS_INMUEBLE = 1
MAX_FOTOS_INMUEBLE = 10


class EstadoInmueble(StrEnum):
    """Lifecycle states of a published `Inmueble` (spec.md, `INMUEBLE.estado`
    in `docs/architecture/architecture.md`).

    - `DISPONIBLE`: visible and open for solicitudes; the only state assigned
      at creation time (no manual review step).
    - `OCULTO`: voluntarily hidden by the propietario (`despublicar`); can be
      brought back with `republicar`.
    - `NO_DISPONIBLE`: set once an arrendamiento is active over the inmueble.
      Reached via `marcar_no_disponible`, invoked by a future `arrendamiento`
      use case (out of scope for HU-001, see design.md decisión 4).
    """

    DISPONIBLE = "disponible"
    NO_DISPONIBLE = "no_disponible"
    OCULTO = "oculto"


@dataclass
class Inmueble:
    """Aggregate root for a property listing.

    Instances must be built through `Inmueble.crear`, which enforces every
    creation-time invariant and always starts the entity in
    `EstadoInmueble.DISPONIBLE` (spec.md: "Estado inicial de la publicación").

    `id` is `None` until a repository assigns one on insert — per
    `docs/architecture/architecture.md`'s sequence diagram, the identifier is
    generated by PostgreSQL, not by the domain.
    """

    propietario_id: uuid.UUID
    direccion: str
    barrio: str
    ciudad: str
    tipo: str
    area_m2: Decimal
    habitaciones: int
    banos: int
    valor_mensual: Decimal
    descripcion: str
    fotos: list[FotoInmueble]
    estado: EstadoInmueble
    id: uuid.UUID | None = None
    agente_id: uuid.UUID | None = None

    @classmethod
    def crear(
        cls,
        *,
        propietario_id: uuid.UUID,
        direccion: str,
        barrio: str,
        ciudad: str,
        tipo: str,
        area_m2: Decimal,
        habitaciones: int,
        banos: int,
        valor_mensual: Decimal,
        descripcion: str,
        fotos: list[FotoInmueble],
        agente_id: uuid.UUID | None = None,
    ) -> Inmueble:
        """Validate business invariants and create a new listing.

        `agente_id` (hu-002, design.md decisión 4) is stored as-is with no
        business validation — agencia<->propietario authorization is
        resolved before reaching this factory.

        Raises `DomainValidationError` when:
        - `valor_mensual` is not strictly positive.
        - `habitaciones` or `banos` is negative.
        - the number of `fotos` is outside
          `[MIN_FOTOS_INMUEBLE, MAX_FOTOS_INMUEBLE]`.
        """
        cls._validar_datos(valor_mensual=valor_mensual, habitaciones=habitaciones, banos=banos)
        if not (MIN_FOTOS_INMUEBLE <= len(fotos) <= MAX_FOTOS_INMUEBLE):
            raise DomainValidationError(
                f"fotos count must be between {MIN_FOTOS_INMUEBLE} and "
                f"{MAX_FOTOS_INMUEBLE}, got {len(fotos)}"
            )

        return cls(
            propietario_id=propietario_id,
            direccion=direccion,
            barrio=barrio,
            ciudad=ciudad,
            tipo=tipo,
            area_m2=area_m2,
            habitaciones=habitaciones,
            banos=banos,
            valor_mensual=valor_mensual,
            descripcion=descripcion,
            fotos=fotos,
            estado=EstadoInmueble.DISPONIBLE,
            agente_id=agente_id,
        )

    @staticmethod
    def _validar_datos(*, valor_mensual: Decimal, habitaciones: int, banos: int) -> None:
        """Shared invariant checks for `crear` and `actualizar_datos`.

        Raises `DomainValidationError` when:
        - `valor_mensual` is not strictly positive.
        - `habitaciones` or `banos` is negative.
        """
        if valor_mensual <= 0:
            raise DomainValidationError("valor_mensual must be greater than zero")
        if habitaciones < 0:
            raise DomainValidationError("habitaciones cannot be negative")
        if banos < 0:
            raise DomainValidationError("banos cannot be negative")

    def actualizar_datos(
        self,
        *,
        direccion: str,
        barrio: str,
        ciudad: str,
        tipo: str,
        area_m2: Decimal,
        habitaciones: int,
        banos: int,
        valor_mensual: Decimal,
        descripcion: str,
    ) -> None:
        """Apply an edit to this listing's data (spec.md: "Edición de
        inmueble publicado"), re-validating the same invariants enforced by
        `crear`.

        Raises `DomainValidationError` when `valor_mensual` is not strictly
        positive or `habitaciones`/`banos` is negative — in that case no
        field is mutated.
        """
        self._validar_datos(valor_mensual=valor_mensual, habitaciones=habitaciones, banos=banos)

        self.direccion = direccion
        self.barrio = barrio
        self.ciudad = ciudad
        self.tipo = tipo
        self.area_m2 = area_m2
        self.habitaciones = habitaciones
        self.banos = banos
        self.valor_mensual = valor_mensual
        self.descripcion = descripcion

    def despublicar(self) -> None:
        """Hide the listing without deleting it (spec.md: "Despublicación
        temporal del inmueble")."""
        self.estado = EstadoInmueble.OCULTO

    def republicar(self) -> None:
        """Bring a hidden (`OCULTO`) listing back to `DISPONIBLE`."""
        self.estado = EstadoInmueble.DISPONIBLE

    def marcar_no_disponible(self) -> None:
        """Mark the listing as `NO_DISPONIBLE`.

        Called directly by the future `arrendamiento` use case when a
        contract is signed over this inmueble (design.md decisión 4: a
        synchronous in-process call, not an event listener).
        """
        self.estado = EstadoInmueble.NO_DISPONIBLE
