"""Outbound ports for the `firma-contrato` domain.

`Protocol`s (structural typing), same rationale as
`seguro_arrendamiento/domain/ports.py` and `identidad/domain/ports.py` —
adapters only need to match the shape, not inherit from a common base.
Methods are `async` for the same reason: the project's persistence layer
and any HTTP-backed adapter are built on async I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from firma_contrato.domain.arrendamiento_activo import ArrendamientoActivo
from firma_contrato.domain.contrato import Contrato


@dataclass
class ResultadoEnvioFirma:
    """Outcome of a single call to a `ProveedorFirmaElectronicaPort`
    adapter's `enviar_a_firma`.

    `referencia_externa` is the proveedor's own tracking id for the firma
    process (kept for audit/dispute purposes, same rationale as
    `seguro_arrendamiento.domain.ports.ResultadoPoliza.referencia_externa`).
    The actual firma result (firmado/rechazado/expirado) is not part of
    this dataclass — per design.md's flow, that arrives later, out of band,
    via the webhook (`ResultadoFirmaWebhook` below).
    """

    referencia_externa: str


@dataclass
class ResultadoFirmaWebhook:
    """The payload a proveedor de firma electrónica reports back (via
    webhook) once a firma process reaches a terminal outcome.

    `estado` is one of `"firmado"`, `"rechazado"`, `"expirado"` —
    intentionally a plain `str` (not `EstadoContrato`) since this is the
    proveedor's own vocabulary, mapped onto `EstadoContrato` inside
    `firma_contrato.application.procesar_resultado_firma`, not here.
    """

    referencia_externa: str
    estado: str


class ProveedorFirmaElectronicaPort(Protocol):
    """Contract every firma electrónica provider adapter must satisfy
    (`FakeAdapter` for dev/test, `ViafirmaAdapter` for prod).

    Per design.md decisión 2, this port only ever receives the document
    already generated by Rentame's own template — it never generates legal
    content itself, only forwards the document to gestionar el proceso de
    firma (envío, tracking).

    Raises `firma_contrato.domain.exceptions.EnvioFirmaNoDisponible` when
    the external provider cannot be reached (timeout/network/unexpected
    response) — never lets that failure surface as an unhandled exception,
    so the API layer can map it to an explicit "envío a firma no
    disponible" response instead of a 500.
    """

    async def enviar_a_firma(self, *, documento: str) -> ResultadoEnvioFirma: ...


class ContratoRepositoryPort(Protocol):
    """Persistence contract for the `Contrato` aggregate."""

    async def guardar(self, contrato: Contrato) -> Contrato:
        """Insert a new `Contrato` and return it with `id` set."""
        ...

    async def actualizar(self, contrato: Contrato) -> Contrato:
        """Persist a state change on an already-existing `Contrato`."""
        ...

    async def obtener_por_referencia_externa(
        self, referencia_externa: str
    ) -> Contrato | None:
        """Return the `Contrato` whose `referencia_externa` matches, used
        by the webhook to locate which contrato a proveedor's payload
        refers to. `None` if no contrato has that referencia."""
        ...

    async def listar_por_usuario(self, usuario_id: UUID) -> list[Contrato]:
        """Return every `Contrato` belonging to `usuario_id` (empty list
        if it has none)."""
        ...


class ArrendamientoActivoRepositoryPort(Protocol):
    """Persistence contract for the `ArrendamientoActivo` aggregate."""

    async def guardar(self, arrendamiento: ArrendamientoActivo) -> ArrendamientoActivo:
        """Insert a new `ArrendamientoActivo` and return it with `id`
        set."""
        ...

    async def listar_por_usuario(self, usuario_id: UUID) -> list[ArrendamientoActivo]:
        """Return every `ArrendamientoActivo` belonging to `usuario_id`
        (empty list if it has none)."""
        ...


class PolizaArrendamientoPort(Protocol):
    """Read-only view this domain uses to check
    `PolizaArrendamiento.estado` without depending on
    `seguro_arrendamiento`'s infrastructure directly — same rationale as
    `seguro_arrendamiento.domain.ports.UsuarioIdentidadPort` for reading
    `usuario.identidad_verificada` (design.md decisión 5).

    This domain only ever reads the estado (proposal.md Impact: "lectura de
    PolizaArrendamiento ... sin modificarlo") — no method here can change
    it.
    """

    async def obtener_poliza_aprobada(self, usuario_id: UUID) -> UUID | None:
        """Return the `id` of an approved (`estado == "aprobada"`)
        `PolizaArrendamiento` belonging to `usuario_id`, or `None` if it
        has none. When an account has more than one approved póliza, an
        implementation may return any single one — this domain only needs
        one to gate on and to link the resulting `Contrato` to."""
        ...
