"""create inmueble and foto_inmueble tables

Revision ID: 8302335a8c95
Revises: 67b705a0042c
Create Date: 2026-08-19 10:38:39.061829

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8302335a8c95"
down_revision: str | Sequence[str] | None = "67b705a0042c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inmueble",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("propietario_id", sa.UUID(), nullable=False),
        sa.Column("agente_id", sa.UUID(), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column("barrio", sa.String(length=255), nullable=False),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("area_m2", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("habitaciones", sa.Integer(), nullable=False),
        sa.Column("banos", sa.Integer(), nullable=False),
        sa.Column("valor_mensual", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agente_id"], ["usuario.id"]),
        sa.ForeignKeyConstraint(["propietario_id"], ["usuario.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "foto_inmueble",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inmueble_id", sa.UUID(), nullable=False),
        sa.Column("url_storage", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("es_principal", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["inmueble_id"], ["inmueble.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("foto_inmueble")
    op.drop_table("inmueble")
    # ### end Alembic commands ###
