"""add password_hash and nombre to usuario

Revision ID: 88258bd709c5
Revises: cee22f50164a
Create Date: 2026-08-22 05:42:06.493700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88258bd709c5"
down_revision: str | Sequence[str] | None = "cee22f50164a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuario", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column("usuario", sa.Column("nombre", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "nombre")
    op.drop_column("usuario", "password_hash")
    # ### end Alembic commands ###
