"""create agencia solicitud_ingreso_agencia relacion_agencia_propietario tables

Revision ID: cee22f50164a
Revises: 8302335a8c95
Create Date: 2026-08-21 03:04:21.298221

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cee22f50164a"
down_revision: str | Sequence[str] | None = "8302335a8c95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("razon_social", sa.String(length=255), nullable=False),
        sa.Column("nit", sa.String(length=50), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relacion_agencia_propietario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agencia_id", sa.UUID(), nullable=False),
        sa.Column("propietario_id", sa.UUID(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("agente_responsable_id", sa.UUID(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["agencia_id"], ["agencia.id"]),
        sa.ForeignKeyConstraint(["agente_responsable_id"], ["usuario.id"]),
        sa.ForeignKeyConstraint(["propietario_id"], ["usuario.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "solicitud_ingreso_agencia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agencia_id", sa.UUID(), nullable=False),
        sa.Column("agente_id", sa.UUID(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["agencia_id"], ["agencia.id"]),
        sa.ForeignKeyConstraint(["agente_id"], ["usuario.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("usuario", sa.Column("agencia_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_usuario_agencia_id_agencia", "usuario", "agencia", ["agencia_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_usuario_agencia_id_agencia", "usuario", type_="foreignkey")
    op.drop_column("usuario", "agencia_id")
    op.drop_table("solicitud_ingreso_agencia")
    op.drop_table("relacion_agencia_propietario")
    op.drop_table("agencia")
    # ### end Alembic commands ###
